name: Update RSS Feed

on:
  **schedule:**
    **- cron: "0 0 * * *"**  # Daily at midnight UTC
  **workflow_dispatch:**     # Manual trigger

jobs:
  update-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run scraper script
        run: python scrape.py

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --localユーザー名 "GitHub Action"
          git add stremio_news.xml
          git commit -m "Update RSS feed" || echo "No changes to commit"
          git push